name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Bump type
        required: true
        type: choice
        options:
          - next
          - patch
          - minor
          - major
          - beta-prepatch
          - beta-preminor
          - beta-premajor
          - alpha-prepatch
          - alpha-preminor
          - alpha-premajor

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - id: extract
        shell: bash
        run: |
          BUMP="${{ github.event.inputs.bump }}"

          if [[ $BUMP =~ ^([a-z]+)|([a-z]+)-([a-z]+)$ ]]; then
            echo "bump=${BASH_REMATCH[1]}${BASH_REMATCH[3]}" >> $GITHUB_OUTPUT
            echo "tag=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          else
            echo "INVALID BUMP TYPE: $VERSION" >&2
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - run: pnpm install

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: pnpm dlx bumpp -r --yes ${{ steps.extract.outputs.bump }} --preid=${{ steps.extract.outputs.tag }}

      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm --filter='./packages/*' -r publish --tag="${{ steps.extract.outputs.tag || 'latest' }}"

      - run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
