name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump (e.g., 4.0.0, 4.1.0-alpha.0, 5.0.0-beta.1)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - id: validate-version
        shell: bash
        run: |
          VERSION="${{ github.event.inputs.version }}"

          if [[ $VERSION =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([a-zA-Z]+)\.(0|[1-9][0-9]*))?$ ]]; then
            echo "major=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "minor=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
            echo "patch=${BASH_REMATCH[3]}" >> $GITHUB_OUTPUT
            echo "tag=${BASH_REMATCH[5]}" >> $GITHUB_OUTPUT
            echo "number=${BASH_REMATCH[6]}" >> $GITHUB_OUTPUT
          else
            echo "INVALID VERSION FORMAT: $VERSION" >&2
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - run: pnpm install

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: pnpm dlx bumpp -r --yes ${{ github.event.inputs.version }}

      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Packages
        run: |
          if [ -n "${{ steps.validate-version.outputs.tag }}" ]; then
            pnpm --filter='./packages/*' -r publish --tag="${{ steps.validate-version.outputs.tag }}"
          else
            pnpm --filter='./packages/*' -r publish
          fi

      - run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
